name: graphika                         # название приложения
description: A new Flutter project.    # описание приложения

publish_to: 'none' 

version: 1.0.0+1                       # версия проекта

environment:
  sdk: ">=2.16.0 <3.0.0"               # версия SDK 

dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.2  
  firebase_core: ^1.10.6               # подключенный плагин для работы с firebase 
  cloud_firestore:                     # подключенный плагин для работы с firebase firestore (базы данных)
  google_maps_flutter: 
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  